export type MembersMessages = {
  memberManagement: string;
  avatar: string;
  email: string;
  username: string;
  role: string;
  manager: string;
  developer: string;
  reporter: string;
  viewer: string;
  client: string;
  lead: string;
  leadReviewer: string;
  leadApprover: string;
  delete: string;
  deleteMember: string;
  noMembersFound: string;
  addMember: string;
  userNameOrEmail: string;
  close: string;
  add: string;
  areYouSure: string;
};
